apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: webprod
data:
  ports.conf: |
    Listen 8080
  default.conf: |
    # Load required modules
    LoadModule rewrite_module /usr/lib/apache2/modules/mod_rewrite.so
    LoadModule headers_module /usr/lib/apache2/modules/mod_headers.so
    LoadModule env_module /usr/lib/apache2/modules/mod_env.so

    <VirtualHost *:8080>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ServerName dev.santaclarautah.gov
        ServerAlias www.dev.santaclarautah.gov

        # Trust Cloudflare headers
        SetEnvIf X-Forwarded-Proto https HTTPS=on
        SetEnvIf X-Forwarded-Host ".*" HTTP_HOST=$0
        RequestHeader set Host "%{HTTP_HOST}e" env=HTTP_HOST

        # Handle Cloudflare SSL
        SetEnvIf CF-Visitor "\"scheme\":\"https\"" HTTPS=on
        SetEnvIf X-Forwarded-Proto "https" HTTPS=on
        RequestHeader set X-Forwarded-Proto "https" env=HTTPS
        RequestHeader set X-Forwarded-Port "443" env=HTTPS

        <Directory /var/www/html>
            Options FollowSymLinks
            AllowOverride None
            Require all granted

            # Handle WordPress permalinks
            RewriteEngine On
            RewriteBase /

            # Ensure proper SSL handling
            RewriteCond %{HTTP:X-Forwarded-Proto} =https
            RewriteRule ^ - [E=HTTPS:on,E=SERVER_PORT:443]

            # WordPress rules
            RewriteRule ^index\.php$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.php [L]
        </Directory>

        # Logging
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost> 