apiVersion: v1
kind: Secret
metadata:
  name: santaclarautah-wordpress-secrets
  namespace: webprod
type: Opaque
data:
  # These values should be base64 encoded
  WORDPRESS_AUTH_KEY: <base64_encoded_value>
  WORDPRESS_SECURE_AUTH_KEY: <base64_encoded_value>
  WORDPRESS_LOGGED_IN_KEY: <base64_encoded_value>
  WORDPRESS_NONCE_KEY: <base64_encoded_value>
  WORDPRESS_AUTH_SALT: <base64_encoded_value>
  WORDPRESS_SECURE_AUTH_SALT: <base64_encoded_value>
  WORDPRESS_LOGGED_IN_SALT: <base64_encoded_value>
  WORDPRESS_NONCE_SALT: <base64_encoded_value> 